### ISSUE TITLE
Build errors (boring-sys-imp-4.9.1)

### ISSUE THREAD

**Issue by deedy5** [0x676e67/rquest#102]
After updating `rquest` to version `v0.20.0` **boring-sys-imp-4.9.1** build errors appeared:

**linux_aarch64**: https://github.com/deedy5/primp/actions/runs/10288267395/job/28473293121#step:4:523
`      cc: error: unrecognized command-line option ‘--target=aarch64-unknown-linux-gnu’`

**musl_aarch64**: https://github.com/deedy5/primp/actions/runs/10288267395/job/28473292464#step:5:1078
`  Unable to generate bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")`

**windows_x64**: https://github.com/deedy5/primp/actions/runs/10288267395/job/28473293752#step:5:421
`  error: can't open patch '//?/C:/Users/runneradmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.1/patches/boringssl-old-ciphers.patch': No such file or directory`

**Comment by 0x676e67** [comment]
The upstream build of version 4.x has undergone major changes, and the specific changes are unknown. The build of git on Windows does not support NUC path, so the patch fails. Linux lacks related local C library tool dependencies

**Comment by deedy5** [comment]
`windows_x64` builds normally after the update

**Comment by deedy5** [comment]
I installed the dependencies, now some new error: `error adding symbols: File in wrong format`
### linux_aarch64 
https://github.com/deedy5/primp/actions/runs/10331142821/job/28600991836
```python
error: linking with `aarch64-unknown-linux-gnu-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/aarch64-unknown-linux-gnu/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:/opt/python/cp311-cp311/bin:/opt/python/cp312-cp312/bin" VSLANG="1033" "aarch64-unknown-linux-gnu-gcc" "-Wl,--version-script=/tmp/rustcpskfSH/list" "-Wl,--no-undefined-version" "/tmp/rustcpskfSH/symbols.o" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/deps/primp.primp.1499765f8c04f078-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/deps" "-L" "/home/runner/work/primp/primp/target/release/deps" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/build/zstd-sys-acf83db154fd609e/out" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/build/boring-sys-imp-69636bd0e9cf89ef/out/build/crypto/" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/build/boring-sys-imp-69636bd0e9cf89ef/out/build/ssl/" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/build/boring-sys-imp-69636bd0e9cf89ef/out/build/" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcpskfSH/libzstd_sys-764851fb4fcaa1dd.rlib" "/tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-d799153064afd554.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-gnu/release/deps/libprimp.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: warning: /tmp/rustcpskfSH/symbols.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/aarch64-unknown-linux-gnu/lib/gcc/aarch64-unknown-linux-gnu/7.5.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /tmp/rustcpskfSH/libboring_sys_imp-c4c7fbe25cc9a325.rlib: error adding symbols: File in wrong format
          collect2: error: ld returned 1 exit status
          

error: could not compile `primp` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO "cargo" "rustc" "--features" "pyo3/extension-module" "--target" "aarch64-unknown-linux-gnu" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/runner/work/primp/primp/Cargo.toml" "--release" "--lib"`
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
Error: The process '/usr/bin/docker' failed with exit code 1
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

### musl_aarch64
https://github.com/deedy5/primp/actions/runs/10331142821/job/28600991902
```python3
 error: linking with `aarch64-unknown-linux-musl-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.cargo/bin:/root/.cargo/bin:/usr/local/musl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:/opt/python/cp311-cp311/bin:/opt/python/cp312-cp312/bin" VSLANG="1033" "aarch64-unknown-linux-musl-gcc" "-Wl,--version-script=/tmp/rustcpCuH4r/list" "-Wl,--no-undefined-version" "/tmp/rustcpCuH4r/symbols.o" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/deps/primp.primp.9a351de43e1172df-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/deps" "-L" "/home/runner/work/primp/primp/target/release/deps" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/build/zstd-sys-54487670b65694a9/out" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/build/boring-sys-imp-20b11d99cb63076e/out/build/crypto/" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/build/boring-sys-imp-20b11d99cb63076e/out/build/ssl/" "-L" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/build/boring-sys-imp-20b11d99cb63076e/out/build/" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/tmp/rustcpCuH4r/libzstd_sys-6f66a624e7c1e5be.rlib" "/tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-74fdc1133fe8b5aa.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-o" "/home/runner/work/primp/primp/target/aarch64-unknown-linux-musl/release/deps/libprimp.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib(bio.c.o): Relocations in generic ELF (EM: 62)
          /usr/local/musl/bin/../lib/gcc/aarch64-unknown-linux-musl/9.4.0/../../../../aarch64-unknown-linux-musl/bin/ld: /tmp/rustcpCuH4r/libboring_sys_imp-40999c6361c14d86.rlib: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
          

error: could not compile `primp` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO CARGO_ENCODED_RUSTFLAGS="-C\u{1f}target-feature=-crt-static" "cargo" "rustc" "--features" "pyo3/extension-module" "--target" "aarch64-unknown-linux-musl" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/runner/work/primp/primp/Cargo.toml" "--release" "--lib"`
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by 0x676e67** [comment]
This looks like the compilation platform is inconsistent with the CPU architecture

**Comment by deedy5** [comment]
`Caused by: Your library is not manylinux_2_28 compliant because of the presence of too-recent versioned symbols: ["libc.so.6 offending versions: GLIBC_2.34, GLIBC_2.33"]. Consider building in a manylinux docker container`

**linux aarch64** builds successfully only with glibc 2.34

**Comment by okeyzero** [comment]
Can you tell me exactly how to fix it? I also encountered this problem "error: failed to run custom build command for `boring-sys-imp v4.9.1`", then I executed the following commands
`git clone "https://boringssl.googlesource.com/boringssl"`
`cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Release`
`ninja -C build`
Then I build my own project again, and it still fails.

**Comment by 0x676e67** [comment]
> Can you tell me exactly how to fix it? I also encountered this problem "error: failed to run custom build command for `boring-sys-imp v4.9.1`", then I executed the following commands `git clone "https://boringssl.googlesource.com/boringssl"` `cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Release` `ninja -C build` Then I build my own project again, and it still fails.

I'm not sure what the error is, maybe you didn't install the environment correctly, maybe you need to install cmake? Please post the complete error log
