### ISSUE TITLE
0.11.99 Connect Error

### ISSUE THREAD

**Issue by nekomiya-hinata** [0x676e67/rquest#79]
There seems to be a problem with the safari
I tried safari 17.0 & safari 17.5 and both reported errors: `error trying to connect: [DUPLICATE_SIGNATURE_ALGORITHM]`

**Comment by 0x676e67** [comment]
no problem 
<img width="939" alt="image" src="https://github.com/user-attachments/assets/d118a83d-755d-4591-bfa8-6de513adbc38">

**Comment by nekomiya-hinata** [comment]
looks only the safari family have this problem, others are normal

**Comment by nekomiya-hinata** [comment]
I tried windows compiled and running without this problem, but ubuntu compiled with the above error

**Comment by nekomiya-hinata** [comment]
v0.11.101 fixed `[DUPLICATE_SIGNATURE_ALGORITHM]` problem

but windows compiled comes up with the following error (linux is fine):
```
  Initialized empty Git repository in D:/DevFiles/Coding/rust/ninja/target/debug/build/boring-sys-imp-9a3bd1487a1d1568/out/boringssl/.git/
  cargo:warning=applying old ciphers patch to boringssl
  --- stderr
  error: can't open patch '//?/C:/Users/nekomiya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-4.9.1/patches/boringssl-old-ciphers.patch': No such file or directory
  thread 'main' panicked at C:\Users\nekomiya\.cargo\registry\src\index.crates.io-6f17d22bba15001f\boring-sys-imp-4.9.1\build/main.rs:572:44:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "\"git\" \"apply\" \"-v\" \"--whitespace=fix\" \"\\\\\\\\?\\\\C:\\\\Users\\\\nekomiya\\\\.cargo\\\\registry\\\\src\\\\index.crates.io-6f17d22bba15001f\\\\boring-sys-imp-4.9.1\\\\patches\\\\boringssl-old-ciphers.patch\" exited with status: 128" }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\result.rs:1679
     3: build_script_main::built_boring_source_path::{{closure}}
     4: std::sync::once_lock::OnceLock<T>::get_or_init
     5: std::sync::once_lock::OnceLock<T>::initialize::{{closure}}
     6: std::sync::once::Once::call_once_force::{{closure}}
     7: std::sys::sync::once::queue::Once::call
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\sys\sync\once\queue.rs:183
     8: std::sync::once::Once::call_once_force
     9: std::rt::lang_start::{{closure}}
    10: std::sync::once_lock::OnceLock<T>::get_or_init
    11: std::sync::once_lock::OnceLock<T>::get_or_init
    12: build_script_main::pick_best_android_ndk_toolchain::{{closure}}::{{closure}}
    13: build_script_main::built_boring_source_path::{{closure}}
    14: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  ```

**Comment by 0x676e67** [comment]
If you compile the upstream boring patch, it will not be supported on Windows. I am too lazy to support it. I recommend Linux cross-compilation, don't use Windows for development.

**Comment by nekomiya-hinata** [comment]
got it, thanks!
It might be better to put this in the readme, to avoid people asking about it again.
